spring.application.name=email-writer

spring.ai.openai.api-key=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
spring.ai.openai.base-url=https://api.groq.com/openai/v1
spring.ai.openai.chat.options.model=llama-3.1-8b-instant
